set(CFX_PLATFORM_MAC OFF)
set(CFX_PLATFORM_WIN OFF)
set(CFX_PLATFORM_UNKNOWN OFF)

if(APPLE)
    set(CFX_PLATFORM_MAC ON)
    set(CFX_PLATFORM_NAME "macos")
elseif(WIN32)
    set(CFX_PLATFORM_WIN ON)
    set(CFX_PLATFORM_NAME "windows")
else()
    set(CFX_PLATFORM_UNKNOWN ON)
    set(CFX_PLATFORM_NAME "unknown")
    message(WARNING "CrossFlow-X: unrecognized platform; only macOS and Windows are supported")
endif()

message(STATUS "CrossFlow-X platform: ${CFX_PLATFORM_NAME}")

if(CFX_PLATFORM_MAC)
    set(CFX_PLATFORM_LINK_TARGET cfx_platform_mac)
elseif(CFX_PLATFORM_WIN)
    set(CFX_PLATFORM_LINK_TARGET cfx_platform_win)
else()
    set(CFX_PLATFORM_LINK_TARGET "")
endif()